name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Run OpenAPI lint with vacuum
        if: github.event_name == 'pull_request'
        uses: pb33f/vacuum-action@v2
        with:
          openapi_path: "bundle/specification.yaml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Vacuum
        if: github.event_name != 'pull_request'
        run: npm run lint -- --pipeline-output